apiVersion: apps/v1
kind: Deployment
metadata:
  name: fakestore-deployment
  namespace: fakestore-namespace
  labels:
    app: fakestore
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fakestore
  template:
    metadata:
      labels:
        app: fakestore
    spec:
      containers:
        - name: fakestore-container
          image: saulhm/fakestoreapi-ui
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: fakestore-service
  namespace: fakestore-namespace
spec:
  type: NodePort
  selector:
    app: fakestore
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30008

